/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

export interface Card {
  id: string;
  word: string; // The primary guess word in Bangla
  englishTranslit: string; // Dynamic english phonetic pronunciation or translation
  tabooWords: string[]; // Avoid mentioning these words during game
  category: string; // Category keyword
  funHint: string; // A humorous hint in Bangla/English
}

export interface Category {
  id: string;
  nameBangla: string;
  nameEnglish: string;
  icon: string; // Lucide icon keyword
  color: string; // Tailwind tint
  borderColor: string;
  textColor: string;
  glowColor: string;
}

export const CATEGORIES: Category[] = [
  {
    id: "movies_series",
    nameBangla: "মুভি ও সিরিজ",
    nameEnglish: "Movies & Series",
    icon: "Film",
    color: "bg-pink-950/40",
    borderColor: "border-pink-500",
    textColor: "text-pink-400",
    glowColor: "glow-border-pink"
  },
  {
    id: "celebrities_creators",
    nameBangla: "সেলিব্রিটি ও ক্রিয়েটর",
    nameEnglish: "Celebrities & Creators",
    icon: "Tv",
    color: "bg-blue-950/40",
    borderColor: "border-blue-500",
    textColor: "text-blue-400",
    glowColor: "glow-border-blue"
  },
  {
    id: "dhaka_memes_slang",
    nameBangla: "মেম ও জেন-জি স্ল্যাং",
    nameEnglish: "Dhaka Gen-Z Memes & Slang",
    icon: "Sparkles",
    color: "bg-purple-950/40",
    borderColor: "border-purple-500",
    textColor: "text-purple-400",
    glowColor: "glow-border-purple"
  },
  {
    id: "food_culture",
    nameBangla: "খাবার ও সংস্কৃতি",
    nameEnglish: "Food & Culture",
    icon: "Utensils",
    color: "bg-yellow-950/40",
    borderColor: "border-yellow-500",
    textColor: "text-yellow-400",
    glowColor: "glow-border-pink"
  }
];

export const DEFAULT_CARDS: Card[] = [
  // ==========================================
  // CATEGORY 1: MOVIES_SERIES (80 unique cards)
  // ==========================================
  { id: "ms_1", word: "হাওয়া", englishTranslit: "Hawa", tabooWords: ["সাদা", "পাখি", "নৌকা", "চঞ্চল"], category: "movies_series", funHint: "Mystery thriller featuring 'Gulti' and the iconic song Shada Shada Kala Kala" },
  { id: "ms_2", word: "তুফান", englishTranslit: "Toofan", tabooWords: ["শাকিব", "ডন", "অ্যাকশন", "চুল"], category: "movies_series", funHint: "2024 blockbuster featuring stylish sunglasses, vintage coats, and Shakib Khan" },
  { id: "ms_3", word: "আয়নাবাজি", englishTranslit: "Aynabaji", tabooWords: ["জেলखाना", "চৌধুরী", "কোকিল", "আয়না"], category: "movies_series", funHint: "Chanchal Chowdhury swaps faces to spend jail sentences for corrupt politicians" },
  { id: "ms_4", word: "ব্যাচেলর পয়েন্ট", englishTranslit: "Bachelor Point", tabooWords: ["কাবিলা", "নোয়াখালী", "পলাশ", "কাজল"], category: "movies_series", funHint: "The viral mega-serial showcasing the hilarious lives of bachelors renting a flat in Dhaka" },
  { id: "ms_5", word: "মহানগর", englishTranslit: "Mohanagar", tabooWords: ["পুলিশ", "ওসি", "থানা", "হারুন"], category: "movies_series", funHint: "OC Harun handles an influential rich brat in a single chaotic night at Kotwali Thana" },
  { id: "ms_6", word: "সুরঙ্গ", englishTranslit: "Shurongo", tabooWords: ["ব্যাংক", "টাকা", "কূপ", "সুড়ঙ্গ"], category: "movies_series", funHint: "A desperate lover digs an underground passage into a secure bank vault" },
  { id: "ms_7", word: "মনপুরা", englishTranslit: "Monpura", tabooWords: ["দ্বীপ", "নৌকা", "গান", "মেতিহা"], category: "movies_series", funHint: "Legendary romantic tragedy on an isolated island with the song Monpura" },
  { id: "ms_8", word: "পথের পাঁচালী", englishTranslit: "Pather Panchali", tabooWords: ["রেলগাড়ি", "অপু", "দুর্গা", "সত্যজিৎ"], category: "movies_series", funHint: "The cinematic masterpiece that put Bengali cinema on the world map" },
  { id: "ms_9", word: "কোথাও কেউ নেই", englishTranslit: "Kothao Keu Nei", tabooWords: ["বাকের", "হুমায়ূন", "মুনা", "ফাঁসি"], category: "movies_series", funHint: "Legendary drama by Humayun Ahmed where citizens marched lines to stop Baker Bhai's hanging" },
  { id: "ms_10", word: "কারাগার", englishTranslit: "Karagar", tabooWords: ["সেল", "চঞ্চল", "মুনতাসির", "সিরিজ"], category: "movies_series", funHint: "A mute prisoner claims he has been locked up for 250 years in cell no. 145" },
  { id: "ms_11", word: "শ্রাবণ মেঘের দিন", englishTranslit: "Srabon Megher Din", tabooWords: ["কুসুম", "হুমায়ূন", "মুক্তা", "গায়ক"], category: "movies_series", funHint: "Beautiful musical movie about tragedy and simple village lives set in Nuhash Polli" },
  { id: "ms_12", word: "দারুচিনি দ্বীপ", englishTranslit: "Daruchini Dwip", tabooWords: ["সেন্টমার্টিন", "ভ্রমণ", "বন্ধু", "সমুদ্র"], category: "movies_series", funHint: "A group of young university friends planning a secret vacation to beach paradise" },
  { id: "ms_13", word: "স্পাইডার-ম্যান", englishTranslit: "Spider-Man", tabooWords: ["মাকড়সা", "পিটার", "জাল", "রেইমি"], category: "movies_series", funHint: "High-school teenager bitten by a genetic spider gets wall-crawling superpowers" },
  { id: "ms_14", word: "হ্যারি পটার", englishTranslit: "Harry Potter", tabooWords: ["যাদু", "হারমায়োনি", "ভলডেমর্ট", "লাঠি"], category: "movies_series", funHint: "The Boy Who Lived attends Hogwarts and fights dark magic wizards" },
  { id: "ms_15", word: "টাইটানিক", englishTranslit: "Titanic", tabooWords: ["জাহাজ", "আইসবর্গ", "জ্যাক", "রোজ"], category: "movies_series", funHint: "The giant unsinkable cruise ship hits an iceberg as young lovers hold hands at the deck" },
  { id: "ms_16", word: "ইনসেপশন", englishTranslit: "Inception", tabooWords: ["স্বপ্ন", "লিওনার্দো", "ঘুরানো", "কোব"], category: "movies_series", funHint: "Christopher Nolan's masterpiece about stealing corporate secrets inside multi-layered dreams" },
  { id: "ms_17", word: "অ্যাভেঞ্জার্স", englishTranslit: "Avengers", tabooWords: ["মার্ভেল", "থানোস", "লোহা", "আমেরিকা"], category: "movies_series", funHint: "Earth's mightiest heroes assemble to reclaim infinity stones from Thanos" },
  { id: "ms_18", word: "ইন্টারস্টেলার", englishTranslit: "Interstellar", tabooWords: ["মহাকাশ", "গ্রহ", "কুপার", "ব্ল্যাকহোল"], category: "movies_series", funHint: "Epic cosmos travel to find a new livable planet through a massive wormhole" },
  { id: "ms_19", word: "বার্বি", englishTranslit: "Barbie", tabooWords: ["পুতুল", "গোলাপী", "মার্গট", "কেন"], category: "movies_series", funHint: "The world of plastic dolls gets a feminist makeover by Greta Gerwig" },
  { id: "ms_20", word: "ওপেনহাইমার", englishTranslit: "Oppenheimer", tabooWords: ["বোমা", "নিউক্লিয়ার", "কিলিয়ান", "জাপান"], category: "movies_series", funHint: "Biopic of J. Robert Oppenheimer, father of the atomic bomb" },
  { id: "ms_21", word: "ডার্ক নাইট", englishTranslit: "The Dark Knight", tabooWords: ["ব্যাটম্যান", "জোকার", "ক্রিশ্চিয়ান", "গোথাম"], category: "movies_series", funHint: "Anarchy rules Gotham City when a clown makeup lunatic creates complete chaos" },
  { id: "ms_22", word: "থ্রি ইডিয়টস", englishTranslit: "3 Idiots", tabooWords: ["আমির", "ইঞ্জিনিয়ার", "ভাইরাস", "র‌্যাঞ্চো"], category: "movies_series", funHint: "Three hostel roommates fight the toxic college grading system in India" },
  { id: "ms_23", word: "দিলওয়ালে দুলহানিয়া লে জায়েঙ্গে", englishTranslit: "DDLJ", tabooWords: ["রাজ", "সিমরান", "ট্রেন", "শাহরুখ"], category: "movies_series", funHint: "Iconic romantic saga where Simran runs to grab Raj's hand at a moving train" },
  { id: "ms_24", word: "বাহুবলী", englishTranslit: "Baahubali", tabooWords: ["কাটাপ্পা", "প্রভাস", "সাম্রাজ্য", "শিবু"], category: "movies_series", funHint: "Grand epic action drama centered around the kingdom of Mahishmati" },
  { id: "ms_25", word: "দঙ্গল", englishTranslit: "Dangal", tabooWords: ["কুস্তি", "আমির", "মেয়ে", "স্বর্ণ"], category: "movies_series", funHint: "Father trains his daughters to win gold medals in female wrestling tournaments" },
  { id: "ms_26", word: "জাওয়ান", englishTranslit: "Jawan", tabooWords: ["শাহরুখ", "সেনা", "পাঁচ", "মেট্রো"], category: "movies_series", funHint: "Shah Rukh Khan wears bandages on his head and hijacks a high speed express train" },
  { id: "ms_27", word: "পিকে", englishTranslit: "PK", tabooWords: ["ভীনগ্রহ", "ভগবান", "লকেট", "আমির"], category: "movies_series", funHint: "An innocent alien gets lost in India and starts questioning local religious gurus" },
  { id: "ms_28", word: "লাগান", englishTranslit: "Lagaan", tabooWords: ["ক্রিকেট", "খাজনা", "ইংরেজ", "আমির"], category: "movies_series", funHint: "Poor villagers play a high stakes cricket match to cancel high colonial taxes" },
  { id: "ms_29", word: "কাবির সিং", englishTranslit: "Kabir Singh", tabooWords: ["ডাক্তার", "মেডিকেল", "প্রীতি", "শহীদ"], category: "movies_series", funHint: "Anger issues medical surgeon gets heartbroken and takes extreme self-destructive steps" },
  { id: "ms_30", word: "নারুটো", englishTranslit: "Naruto", tabooWords: ["নিনজা", "সাসুকে", "নয়", "কাকাসি"], category: "movies_series", funHint: "Spiky orange ninja boy wants to prove his worth and become the Hokage" },
  { id: "ms_31", word: "ওয়ান পিস", englishTranslit: "One Piece", tabooWords: ["জলদস্যু", "লুফি", "রবার", "খাজানা"], category: "movies_series", funHint: "Luffy eats a weird devil fruit and sails out to find the ultimate pirate treasure" },
  { id: "ms_32", word: "ড্রাগন বল জেড", englishTranslit: "Dragon Ball Z", tabooWords: ["গোকু", "ভেজিটা", "সুপার", "বল"], category: "movies_series", funHint: "Super Saiyan warriors defend earth using energy beams and flying clouds" },
  { id: "ms_33", word: "ডেথ নোট", englishTranslit: "Death Note", tabooWords: ["খাতা", "এল", "লাইট", "শিনিগামি"], category: "movies_series", funHint: "High schooler finds a mysterious diary where writing a name kills the person" },
  { id: "ms_34", word: "অ্যাটাক অন টাইটান", englishTranslit: "Attack on Titan", tabooWords: ["দৈত্য", "এলেন", "দেয়াল", "লিভাই"], category: "movies_series", funHint: "Mankind is caged behind colossal stone walls to avoid massive human eaters" },
  { id: "ms_35", word: "পোকেমন", englishTranslit: "Pokemon", tabooWords: ["পিকাচু", "অ্যাশ", "বল", "পকেট"], category: "movies_series", funHint: "Ash Ketchum travels the world with electronic pocket monsters in small red balls" },
  { id: "ms_36", word: "ডোরেমন", englishTranslit: "Doraemon", tabooWords: ["বিড়াল", "নোবিতা", "পকেট", "শিজুকা"], category: "movies_series", funHint: "A blue robotic cat from the 22nd century helps a lazy student with unique tools" },
  { id: "ms_37", word: "টম অ্যান্ড জেরি", englishTranslit: "Tom and Jerry", tabooWords: ["বিড়াল", "ইঁদুর", "তাড়া", "কার্টুন"], category: "movies_series", funHint: "Classic chase cartoon of a desperate cat trying to capture a smart mouse" },
  { id: "ms_38", word: "বেন টেন", englishTranslit: "Ben 10", tabooWords: ["ঘড়ি", "এলিয়েন", "চাচা", "অমনিট্রিক্স"], category: "movies_series", funHint: "Boy finds a green extraterrestrial wristwatch that turns him into 10 cool monsters" },
  { id: "ms_39", word: "সিনচ্যান", englishTranslit: "Shin-Chan", tabooWords: ["বাচ্চা", "প্যান্ট", "প্যাঁচা", "মিৎসি"], category: "movies_series", funHint: "Mischievous 5-year-old Japanese kid drives his mom and school principal crazy" },
  { id: "ms_40", word: "স্পঞ্জবব", englishTranslit: "SpongeBob", tabooWords: ["সমুদ্র", "হলুদ", "প্যাট্রিক", "বার্গার"], category: "movies_series", funHint: "A yellow sea sponge lives in a pineapple under the sea and flips delicious patties" },
  { id: "ms_41", word: "ক্র্যাশ ল্যান্ডিং অন ইউ", englishTranslit: "Crash Landing on You", tabooWords: ["উত্তর", "কোরিয়া", "প্যারাসুট", "প্রেম"], category: "movies_series", funHint: "South Korean heiress paraglides into a storm and crash lands in North Korean zone" },
  { id: "ms_42", word: "স্কুইড গেম", englishTranslit: "Squid Game", tabooWords: ["টাকা", "খেলা", "সবুজ", "মুখোশ"], category: "movies_series", funHint: "Debt-ridden players play dangerous children games for a massive cash prize pot" },
  { id: "ms_43", word: "গবলিন", englishTranslit: "Goblin", tabooWords: ["তলোয়ার", "অমর", "কনে", "কোরিয়ান"], category: "movies_series", funHint: "An immortal protector searches for his human bride to pull out a magic chest sword" },
  { id: "ms_44", word: "বিজনেস প্রপোজাল", englishTranslit: "Business Proposal", tabooWords: ["অফিস", "সিনিয়র", "মিথ্যা", "প্রেমী"], category: "movies_series", funHint: "Employee goes on a blind date disguised as her rich best friend and meets her CEO" },
  { id: "ms_45", word: "অল অফ আস আর ডেড", englishTranslit: "All of Us Are Dead", tabooWords: ["জম্বি", "স্কুল", "ভাইরাস", "কোরিয়ান"], category: "movies_series", funHint: "High school campus becomes ground zero for a hyper-contagious zombie apocalypse" },
  { id: "ms_46", word: "স্ট্রেনজার থিংস", englishTranslit: "Stranger Things", tabooWords: ["ইলেভেন", "দানব", "বাচ্চা", " উল্টো"], category: "movies_series", funHint: "Kids with bicycles uncover government sci-fi secrets and a telekinetic girl named Eleven" },
  { id: "ms_47", word: "গেম অফ থ্রোনস", englishTranslit: "Game of Thrones", tabooWords: ["সিংহাসন", "ড্রাগন", "জন", "শীতকাল"], category: "movies_series", funHint: "Noble houses clash for the iron throne while white winter walkers approach the wall" },
  { id: "ms_48", word: "ব্রেকিং ব্যাড", englishTranslit: "Breaking Bad", tabooWords: ["রসায়ন", "ক্যান্সার", "ড্রাগ", "ওয়াল্টার"], category: "movies_series", funHint: "Chemistry school teacher gets cancer and cooks blue high-purity methamphetamine with Jesse" },
  { id: "ms_49", word: "ওয়েডনেসডে", englishTranslit: "Wednesday", tabooWords: ["মেয়ে", "কালো", "নাচ", "হাত"], category: "movies_series", funHint: "Addams family goth daughter investigates monster homicides at Nevermore Academy" },
  { id: "ms_50", word: "ফ্রেন্ডস", englishTranslit: "Friends", tabooWords: ["ক্যাফে", "র‍্যাচেল", "জোয়ি", "চন্দ্রা"], category: "movies_series", funHint: "Six young single adults navigate lifestyle, relationships and jokes in Manhattan" },
  { id: "ms_51", word: "মানি হাইস্ট", englishTranslit: "Money Heist", tabooWords: ["প্রফেসর", "ডাকাতি", "মুখোশ", "স্পেন"], category: "movies_series", funHint: "Masked criminals lock themselves in the Royal Mint of Spain executing Professor's plan" },
  { id: "ms_52", word: "অ্যাভাটার", englishTranslit: "Avatar", tabooWords: ["নীল", "প্যান্ডোরা", "ক্যামেরন", "নৃতাত্ত্বিক"], category: "movies_series", funHint: "Human soldier connects his mind to a tall blue alien body on outer jungle moon Pandora" },
  { id: "ms_53", word: "হোম অ্যালোন", englishTranslit: "Home Alone", tabooWords: ["কেভিন", "ক্রিসমাস", "চোর", "ট্র্যাপ"], category: "movies_series", funHint: "8-year-old boy gets accidentally left behind on Christmas and sets clever traps for local robbers" },
  { id: "ms_54", word: "লাইন অফ ডিউটি", englishTranslit: "Line of Duty", tabooWords: ["পুলিশ", "দুর্নীতি", "তদন্ত", "সিরিজ"], category: "movies_series", funHint: "AC-12 counter-corruption unit tracks down dirty senior police officers" },
  { id: "ms_55", word: "শেরলক হোমসের গল্প", englishTranslit: "Sherlock Holmes", tabooWords: ["গোয়েন্দা", "তদন্ত", "লন্ডন", "ওয়াটসন"], category: "movies_series", funHint: "High-intelligence pipe smoking detective solves cases at 221B Baker Street" },
  { id: "ms_56", word: "জুরাসিক পার্ক", englishTranslit: "Jurassic Park", tabooWords: ["ডাইনোসর", "দ্বীপ", "পার্ক", "অস্থি"], category: "movies_series", funHint: "Wealthy developer invites scientists to a tropical island park of cloned dinosaurs" },
  { id: "ms_57", word: "ফাইন্ডিং নেমো", englishTranslit: "Finding Nemo", tabooWords: ["মাছ", "সমুদ্র", "অস্ট্রেলিয়া", "ডরি"], category: "movies_series", funHint: "Anxious clownfish swims across the vast ocean to find his captured little son" },
  { id: "ms_58", word: "দ্য ক্রাউন", englishTranslit: "The Crown", tabooWords: ["রানী", "এলিজাবেথ", "লন্ডন", "রাজকীয়"], category: "movies_series", funHint: "Netflix drama showing the political and personal life of Queen Elizabeth II" },
  { id: "ms_59", word: "শার্লক", englishTranslit: "Sherlock TV", tabooWords: ["বেনেডিক্ট", "গোয়েন্দা", "ওয়াটসন", "বিজ্ঞান"], category: "movies_series", funHint: "Modern 21st-century English television version of Conan Doyle's sleuth cases" },
  { id: "ms_60", word: "কং ফু পান্ডা", englishTranslit: "Kung Fu Panda", tabooWords: ["পান্ডা", "পো", "বাঘ", "ড্রাগন"], category: "movies_series", funHint: "Plump noodle-slurping panda Po gets chosen as the legendary Dragon Warrior" },
  { id: "ms_61", word: "ম্যাট্রিক্স", englishTranslit: "The Matrix", tabooWords: ["নিও", "বড়ি", "কম্পিউটার", "কালো"], category: "movies_series", funHint: "Hacker chooses the red pill to unlock a virtual simulation cage built by robots" },
  { id: "ms_62", word: "পাইরেটস অফ দ্য ক্যারিবিয়ান", englishTranslit: "Pirates of the Caribbean", tabooWords: ["জাহাজ", "জ্যাক", "ডেপ", "সোনার"], category: "movies_series", funHint: "Captain Jack Sparrow claims he is 'the' absolute legendary ocean smuggler" },
  { id: "ms_63", word: "ব্ল্যাক প্যান্থার", englishTranslit: "Black Panther", tabooWords: ["ওয়াকান্ডা", "রাজা", "কম্পন", "মার্ভেল"], category: "movies_series", funHint: "King T'Challa defends his futuristic, secretive high-tech African kingdom Wakanda" },
  { id: "ms_64", word: "গ্লাডিয়েটর", englishTranslit: "Gladiator", tabooWords: ["রোম", "লড়াই", "তলওয়ার", "রাসেল"], category: "movies_series", funHint: "Enslaved Roman general fights his way through the Coliseum arena for perfect revenge" },
  { id: "ms_65", word: "মুনপুরা টু", englishTranslit: "Monpura 2", tabooWords: ["রোমান্টিক", "গান", "মাঝি", "মেয়ে"], category: "movies_series", funHint: "Rumored or tribute sequel ideas surrounding the epic Bangladeshi delta romance" },
  { id: "ms_66", word: "চিলড্রেন অফ হেভেন", englishTranslit: "Children of Heaven", tabooWords: ["জুতো", "ইরান", "দাউদ", "দৌড়"], category: "movies_series", funHint: "Iranian brother and sister share a single pair of sneakers running to daily school" },
  { id: "ms_67", word: "দিল চাহতা হ্যায়", englishTranslit: "Dil Chahta Hai", tabooWords: ["গোয়া", "বন্ধু", "আমির", "ভ্রমণ"], category: "movies_series", funHint: "Three young childhood friends take a seminal road trip to Goa which changes their lives" },
  { id: "ms_68", word: "কভি খুশি কভি গম", englishTranslit: "K3G", tabooWords: ["পরিবার", "অমিতাভ", "শাহরুখ", "লন্ডন"], category: "movies_series", funHint: "Rich traditional family breaks apart over a wedding and reunites with tears" },
  { id: "ms_69", word: "ডিটেকটিভ ব্যোমকেশ", englishTranslit: "Detective Byomkesh", tabooWords: ["সত্যন্বেষী", "ক্যালকাটা", "পাকড়াশী", "গোয়েন্দা"], category: "movies_series", funHint: "Sharp intellectual Bengali sleuth who prefers to call himself a 'seeker of truth'" },
  { id: "ms_70", word: "জাপানি কার্টুন", englishTranslit: "Japanese Cartoon", tabooWords: ["এনিমে", "জাপান", "আঁকা", "ভাষা"], category: "movies_series", funHint: "Colloquial term uncles and parents use to describe high art anime movies" },
  { id: "ms_71", word: "চোরকি সিরিজ", englishTranslit: "Chorki series", tabooWords: ["ওটিটি", "সিরিজ", "খেলা", "অ্যাপ"], category: "movies_series", funHint: "Popular monthly subscription streaming app of original Bangladeshi web hit dramas" },
  { id: "ms_72", word: "টয় স্টোরি", englishTranslit: "Toy Story", tabooWords: ["খেলনা", "উডি", "ব্লাউজ", "স্পেস"], category: "movies_series", funHint: "Animated classic where toys come alive when their young owner Andy exits the bedroom" },
  { id: "ms_73", word: "শ্রেক", englishTranslit: "Shrek", tabooWords: ["সবুজ", "দৈত্য", "ফিওনা", "গাধা"], category: "movies_series", funHint: "A grumpy green ogre has his peaceful swamp invaded by fairytale refugees" },
  { id: "ms_74", word: "লায়ন কিং", englishTranslit: "The Lion King", tabooWords: ["সিংহ", "সিম্বা", "রাজা", "জঙ্গল"], category: "movies_series", funHint: "Young lion cub Simba flees his savanna home after his father Mufasa is murdered" },
  { id: "ms_75", word: "আয়ান ম্যান", englishTranslit: "Iron Man", tabooWords: ["টনি", "লোহা", " স্যুট", "মার্ভেল"], category: "movies_series", funHint: "Millionaire tech genius Tony Stark builds a flying laser weapon iron armor suit" },
  { id: "ms_76", word: "কাইজার", englishTranslit: "Kaiser OTT", tabooWords: ["ডিটেকটিভ", " গেম", "নিশাত", "ভিডিও"], category: "movies_series", funHint: "Videogame addicted police homicide detective who solves crimes using logic" },
  { id: "ms_77", word: "কেবিন ইন দ্য উডস", englishTranslit: "Cabin in the Woods", tabooWords: ["জঙ্গল", "ভয়", "বাড়ি", "দানব"], category: "movies_series", funHint: "Five friends go to a remote forest cabin which is actually a secret underground lab test" },
  { id: "ms_78", word: "ফাইটিং লায়ন", englishTranslit: "Fight Club", tabooWords: ["ব্র্যাড", "এডওয়ার্ড", "লড়াই", "সোয়াপান"], category: "movies_series", funHint: "Brad Pitt starts a secret underground punches club that turns into a massive anti-consumer group" },
  { id: "ms_79", word: "গোস্ট বাস্টার্স", englishTranslit: "Ghostbusters", tabooWords: ["ভূত", "ভ্যাকুয়াম", "লেজার", "নিউইয়র্ক"], category: "movies_series", funHint: "Four eccentric scientists catch spooky paranormal spirits around Manhattan with laser guns" },
  { id: "ms_80", word: "ফাইন্ডিং ডোরেমন", englishTranslit: "Finding Doraemon", tabooWords: ["জাপানি", "গাধা", "নোবিতা", "পকেট"], category: "movies_series", funHint: "Hilarious fictional fusion kids think of after watching both Disney and Doraemon series" },

  // ==================================================
  // CATEGORY 2: CELEBRITIES_CREATORS (80 unique cards)
  // ==================================================
  { id: "cc_1", word: "আইমান সাদিক", englishTranslit: "Ayman Sadiq", tabooWords: ["ইশকুল", "মিলিটারি", "লেকচার", "উদ্যোক্তা"], category: "celebrities_creators", funHint: "The supreme digital education pioneer who runs 10 Minute School" },
  { id: "cc_2", word: "হিরো আলম", englishTranslit: "Hero Alom", tabooWords: ["মিউজিক", "ভিডিও", "ভোট", "বগুড়া"], category: "celebrities_creators", funHint: "Unstoppable internet celebrity who acts, sings in multiple languages, and runs for parliament" },
  { id: "cc_3", word: "শাকিব খান", englishTranslit: "Shakib Khan", tabooWords: ["সিনেমা", "কিং", "নায়ক", "অপু"], category: "celebrities_creators", funHint: "The undisputed blockbuster King of Dhallywood cinema for over two decades" },
  { id: "cc_4", word: "তাহসান", englishTranslit: "Tahsan Khan", tabooWords: ["গান", "প্রেম", "আলো", "মিথিলা"], category: "celebrities_creators", funHint: "Soulful keyboards romantic singer and elite clean-cut actor of 2000s classics" },
  { id: "cc_5", word: "চঞ্চল চৌধুরী", englishTranslit: "Chanchal Chowdhury", tabooWords: ["আয়নাবাজি", "কারাগার", "তাকদীর", "অভিনয়"], category: "celebrities_creators", funHint: "The highest calibre actor of Bangladesh, known for versatile makeovers in Hawa and Karagar" },
  { id: "cc_6", word: "সোলায়মান সুখন", englishTranslit: "Solaiman Shukhon", tabooWords: ["মোটিভেশন", "ইউটিউব", "চাকরি", "ল্যাপটপ"], category: "celebrities_creators", funHint: "Popular corporate speaker who gives life hacks while holding a glass of juice" },
  { id: "cc_7", word: "রাফসান দ্য ছোটভাই", englishTranslit: "Rafsan The Chotobhai", tabooWords: ["খাবার", "বার্গার", "ইউটিউবার", "ভিডিও"], category: "celebrities_creators", funHint: "Culinary reviewer known for intense enthusiasm and eating loaded gourmet burgers" },
  { id: "cc_8", word: "খালিদ ফারহান", englishTranslit: "Khalid Farhan", tabooWords: ["প্যাসিভ", "মার্কেটিং", "আয়ারল্যান্ড", "টাকা"], category: "celebrities_creators", funHint: "Niche marketer who teaches passive income hacks from Ireland wearing elegant jackets" },
  { id: "cc_9", word: "ড. মাহফুজুর রহমান", englishTranslit: "Dr. Mahfuzur Rahman", tabooWords: ["টিভি", "এটিএন", "গান", "ঈদ"], category: "celebrities_creators", funHint: "Media channel boss who headlines his own solo music concert every single Eid night" },
  { id: "cc_10", word: "হানিফ সংকেত", englishTranslit: "Hanif Sanket", tabooWords: ["ইত্যাদি", "বিটিভি", "কৌতুক", "উপস্থাপক"], category: "celebrities_creators", funHint: "Legendary host of 'Ittadi', known for his fast-rhyming comedic voiceovers" },
  { id: "cc_11", word: "সাকিব আল হাসান", englishTranslit: "Shakib Al Hasan", tabooWords: ["ক্রিকেট", "অলরাউন্ডার", "উইকেট", "অধিনায়ক"], category: "celebrities_creators", funHint: "Legendary No. 1 ICC all-rounder of national cricket team, known for bold behavior" },
  { id: "cc_12", word: "মাশরাফি মর্তুজা", englishTranslit: "Mashrafe Mortaza", tabooWords: ["ক্যাপ্টেন", "নড়াইল", "পেসার", "ক্রিকেট"], category: "celebrities_creators", funHint: "The beloved iconic captain who led Bangladesh cricket to historic victory peaks" },
  { id: "cc_13", word: "রাবা খান", englishTranslit: "Raba Khan", tabooWords: ["বই", "ভিডিও", "হাসি", "ব্র্যান্ড"], category: "celebrities_creators", funHint: "The viral female creator known for hilarious accents and modeling local ethnic wear" },
  { id: "cc_14", word: "মেহজাবিন চৌধুরী", englishTranslit: "Mehazabien Chowdhury", tabooWords: ["নাটক", "কান্না", "অভিনেত্রী", "রোমান্টিক"], category: "celebrities_creators", funHint: "The ultimate queen of TV dramas, famous for highly emotional crying and hit plots" },
  { id: "cc_15", word: "সাদমান সাদিক", englishTranslit: "Sadman Sadik", tabooWords: ["বই", "পড়া", "শেখা", "টেন"], category: "celebrities_creators", funHint: "The calm public educator who teaches study frameworks and writes productivity guides" },
  { id: "cc_16", word: " তৌহিদ আফ্রিদি", englishTranslit: "Towhid Afridi", tabooWords: ["ইউটিউব", "ব্লগ", "প্র্যাঙ্ক", "ভিডিও"], category: "celebrities_creators", funHint: "Super famous lifestyle vlogger and early pioneer of street interview shows" },
  { id: "cc_17", word: "টেলর সুইফট", englishTranslit: "Taylor Swift", tabooWords: ["গান", "প্রেমিক", "কনসার্ট", "সুইফটি"], category: "celebrities_creators", funHint: "Pop mega-star who breaks records with her Era tour and writes breakup tracks" },
  { id: "cc_18", word: "বিটিএস", englishTranslit: "BTS", tabooWords: ["কোরিয়া", "আর্মি", "কেপপ", "ডিনামাইট"], category: "celebrities_creators", funHint: "The iconic South Korean boys group consisting of 7 worldwide heartthrobs" },
  { id: "cc_19", word: "জাস্টিন বিবার", englishTranslit: "Justin Bieber", tabooWords: ["বেবি", "কানাডা", " গায়ক", "সেলেনা"], category: "celebrities_creators", funHint: "Fringe-hair teenager who launched the global song hit Baby and became pop royalty" },
  { id: "cc_20", word: "বিলি আইলিশ", englishTranslit: "Billie Eilish", tabooWords: ["কালো", "সবুজ", "গান", "মেয়ে"], category: "celebrities_creators", funHint: "Whispering vocals pop sensation famous for baggy clothes and green dyed hair" },
  { id: "cc_21", word: "এমিনেম", englishTranslit: "Eminem", tabooWords: ["র‌্যাপ", "দ্রুত", "আমেরিকা", "স্লিম"], category: "celebrities_creators", funHint: "The Rap God who spits thousands of words per minute and wears clean gray hoodies" },
  { id: "cc_22", word: "মাইকেল জ্যাকসন", englishTranslit: "Michael Jackson", tabooWords: ["নাচ", "পপ", "মুনওয়াক", "কিং"], category: "celebrities_creators", funHint: "The King of Pop famous for his flawless moonwalk and shiny single white glove" },
  { id: "cc_23", word: "এড শিরান", englishTranslit: "Ed Sheeran", tabooWords: ["লাল", "গীটার", "শেপ", "গায়ক"], category: "celebrities_creators", funHint: "Ginger-haired boy who plays an acoustic guitar alone and sang Shape of You" },
  { id: "cc_24", word: "ব্রুনো মার্স", englishTranslit: "Bruno Mars", tabooWords: ["টুপি", "নাচ", "ফঙ্ক", "গোল্ড"], category: "celebrities_creators", funHint: "Super active dancer and retro singer who wants to treat you to Uptown Funk" },
  { id: "cc_25", word: "ব্ল্যাকপিঙ্ক", englishTranslit: "BLACKPINK", tabooWords: ["কেপপ", "লিসা", " জেনি", "মেয়ে"], category: "celebrities_creators", funHint: "Korean girls group who sang How You Like That and modeled for top luxury brands" },
  { id: "cc_26", word: "লিওনেল মেসি", englishTranslit: "Lionel Messi", tabooWords: ["আর্জেন্টিনা", "ফুটবল", "বার্সেলোনা", "রোজারিও"], category: "celebrities_creators", funHint: "The little magician from Rosario who won the 2022 World Cup with Argentina" },
  { id: "cc_27", word: "ক্রিশ্চিয়ানো রোনালদো", englishTranslit: "Cristiano Ronaldo", tabooWords: ["পর্তুগাল", "ইউনাইটেড", "রিয়াল", "সুইউউ"], category: "celebrities_creators", funHint: "Portuguese physical beast who yells SIUUU and holds endless goal records" },
  { id: "cc_28", word: "নেইমার জুনিয়র", englishTranslit: "Neymar Jr", tabooWords: ["ব্রাজিল", "পিএসজি", "চুল", "ইনজুরি"], category: "celebrities_creators", funHint: "Brazilian samba dribble genius known for stylish hair and dramatic ankle rolls" },
  { id: "cc_29", word: "বিরাট কোহলি", englishTranslit: "Virat Kohli", tabooWords: ["ভারত", "ক্রিকেট", "আনুশকা", "রয়্যাল"], category: "celebrities_creators", funHint: "Indian batting king and chase master, married to actress Anushka Sharma" },
  { id: "cc_30", word: "মহেন্দ্র সিং ধোনি", englishTranslit: "MS Dhoni", tabooWords: ["অধিনায়ক", "চেন্নাই", "উইকেট", "হেলিকপ্টার"], category: "celebrities_creators", funHint: "Captain Cool who won World Cups with India and hits the famous helicopter shot" },
  { id: "cc_31", word: "মি: বিস্ট", englishTranslit: "MrBeast", tabooWords: ["টাকা", "চ্যালেঞ্জ", "ইউটিউব", "বিস্ট"], category: "celebrities_creators", funHint: "The world's biggest YouTuber who gives away islands and locks people in boxes" },
  { id: "cc_32", word: "পিউডিপাই", englishTranslit: "PewDiePie", tabooWords: ["ইউটিউব", "গেম", "সুইডেন", "টি-সিরিজ"], category: "celebrities_creators", funHint: "Swedish creator who ruled early YouTube gaming and had battle with T-Series" },
  { id: "cc_33", word: "খাবি ল্যামে", englishTranslit: "Khaby Lame", tabooWords: ["টিকটক", "হাত", "নীরব", "ইতালি"], category: "celebrities_creators", funHint: "Silent TikTok star who simplifies complex life hacks using only a simple hand gesture" },
  { id: "cc_34", word: "লোগান পল", englishTranslit: "Logan Paul", tabooWords: ["বক্সিং", "ইউটিউব", "প্রাইম", "পানি"], category: "celebrities_creators", funHint: "Controversial vlogger who sells Prime energy drinks and fights WWE matches" },
  { id: "cc_35", word: "মারকোস ব্রাউনলি", englishTranslit: "MKBHD", tabooWords: ["মোবাইল", "রিভিউ", "টেক", "ইউটিউব"], category: "celebrities_creators", funHint: "The ultimate tech reviewer with crisp clean 8K videos and matte black setup" },
  { id: "cc_36", word: "জ্যাক কিং", englishTranslit: "Zach King", tabooWords: ["যাদু", "সম্পাদনা", "ভিডিও", "ল্যাপটপ"], category: "celebrities_creators", funHint: "Digital video illusionist who performs impossible magic tricks through clever edits" },
  { id: "cc_37", word: "শহীদ আফ্রিদি", englishTranslit: "Shahid Afridi", tabooWords: ["পাকিস্তান", "ক্রিকেট", "ছক্কা", "আউট"], category: "celebrities_creators", funHint: "Boom Boom batsman known for hitting massive sixes and retiring multiple times" },
  { id: "cc_38", word: "শচীন টেন্ডুলকার", englishTranslit: "Sachin Tendulkar", tabooWords: ["ক্রিকেট", "ভারত", "সেঞ্চুরি", "গড"], category: "celebrities_creators", funHint: "The Little Master of cricket who scored 100 international centuries" },
  { id: "cc_39", word: "উসাইন বোল্ট", englishTranslit: "Usain Bolt", tabooWords: ["দৌড়", "গতি", "অলিম্পিক", "জ্যামাইকা"], category: "celebrities_creators", funHint: "The fastest man alive who does the symbolic lightning bolt hand gesture" },
  { id: "cc_40", word: "লেব্রন জেমস", englishTranslit: "LeBron James", tabooWords: ["বাস্কেটবল", "এলএ", "লেটস", "কিং"], category: "celebrities_creators", funHint: "Venerated basketball king often compared to Michael Jordan in GOAT debate" },
  { id: "cc_41", word: "আরিজিৎ সিং", englishTranslit: "Arijit Singh", tabooWords: ["গান", "কান্না", "আশিকী", "রোমান্টিক"], category: "celebrities_creators", funHint: "The soulful voice behind Bollywood's biggest heartbreak ballads and melodies" },
  { id: "cc_42", word: "আতিফ আসলাম", englishTranslit: "Atif Aslam", tabooWords: ["গান", "পাকিস্তান", "তাজদারে", "গীটার"], category: "celebrities_creators", funHint: "Pakistani star rock singer whose high pitch voice ruled Bollywood hits for 15 years" },
  { id: "cc_43", word: "দিলজিৎ দোসাঞ্জ", englishTranslit: "Diljit Dosanjh", tabooWords: ["পাঞ্জাবি", "গায়ক", "পাগড়ি", "কনসার্ট"], category: "celebrities_creators", funHint: "Punjab global icon who performed at Coachella wearing traditional dress" },
  { id: "cc_44", word: "সেলেনা গোমেজ", englishTranslit: "Selena Gomez", tabooWords: ["গান", "জাস্টিন", "ড্রামস", "প্রসাধনী"], category: "celebrities_creators", funHint: "Disney channel child actress turned pop singer who runs Rare Beauty makeup" },
  { id: "cc_45", word: "আরিয়ানা গ্র্যান্ডে", englishTranslit: "Ariana Grande", tabooWords: ["উচ্চ", "গান", "চুল", "পনিটেইল"], category: "celebrities_creators", funHint: "Petite pop vocals powerhouse known for her extremely high ponytail and high pitch notes" },
  { id: "cc_46", word: "দ্যা উইকেন্ড", englishTranslit: "The Weeknd", tabooWords: ["কানাডা", "চোখ", "পপ", "গায়ক"], category: "celebrities_creators", funHint: "Abel Tesfaye, commercial pop singer of Blinding Lights who changed his name" },
  { id: "cc_47", word: "ড্রেইক", englishTranslit: "Drake", tabooWords: ["হিপহপ", "র‌্যাপ", "কানাডা", "মেম"], category: "celebrities_creators", funHint: "Canadian rapper whose orange jacket meme represents rejecting vs accepting things" },
  { id: "cc_48", word: "শাকিরা", englishTranslit: "Shakira", tabooWords: ["নাচ", "গান", "কোমর", "কলম্বিয়া"], category: "celebrities_creators", funHint: "Colombian dance star famous for Waka Waka and promising her hips don't lie" },
  { id: "cc_49", word: "হানি সিং", englishTranslit: "Honey Singh", tabooWords: ["র‌্যাপ", "হিন্দি", "নেশা", "গরম"], category: "celebrities_creators", funHint: "Rap producer who popularized Hindi party club anthems like Blue Eyes and Lungi Dance" },
  { id: "cc_50", word: "বাদশাহ", englishTranslit: "Badshah", tabooWords: ["র‌্যাপ", "চশমা", "হিন্দি", "পাগল"], category: "celebrities_creators", funHint: "Bollywood commercial rapper whose tracks start with 'It's your boy Badshah!'" },
  { id: "cc_51", word: "শাহরুখ খান", englishTranslit: "Shah Rukh Khan", tabooWords: ["কিং", "নায়ক", "বলিউড", "মন্নত"], category: "celebrities_creators", funHint: "The King of Bollywood, famous for his iconic pose with wide outstretched arms" },
  { id: "cc_52", word: "সালমান খান", englishTranslit: "Salman Khan", tabooWords: ["ভাই", "বলিউড", "বিয়ে", "বডি"], category: "celebrities_creators", funHint: "Bollywood's 'Sallu Bhai' known for bodybuilding, Eid movies, and bachelor life" },
  { id: "cc_53", word: "দীপিকা পাডুকোন", englishTranslit: "Deepika Padukone", tabooWords: ["বলিউড", "রণবীর", "মডেল", "অভিনেত্রী"], category: "celebrities_creators", funHint: "Tall gorgeous Bollywood leading lady who starred in Om Shanti Om and Piku" },
  { id: "cc_54", word: "প্রিয়াঙ্কা চোপড়া", englishTranslit: "Priyanka Chopra", tabooWords: ["মিস", "আমেরিকা", "বলিউড", "নিক"], category: "celebrities_creators", funHint: "Former Miss World who migrated to Hollywood and married singer Nick Jonas" },
  { id: "cc_55", word: "কারি মিনাতি", englishTranslit: "CarryMinati", tabooWords: ["ইউটিউব", "রোস্ট", "ভিডিও", "হিন্দি"], category: "celebrities_creators", funHint: "Ajey Nagar, India's top solo roaster who yells 'Toh Kaise Hain Aap Log!'" },
  { id: "cc_56", word: "ধ্রুব রাঠী", englishTranslit: "Dhruv Rathee", tabooWords: ["ইউটিউব", "বিশ্লেষণ", "জার্মানি", "রাজনীতি"], category: "celebrities_creators", funHint: "Indian popular educational vlogger who analyzes political affairs of India" },
  { id: "cc_57", word: "মুশফিকুর রহিম", englishTranslit: "Mushfiqur Rahim", tabooWords: ["ক্রিকেট", "উইকেট", "খাটো", "ব্যাট"], category: "celebrities_creators", funHint: "Bangladesh's premium wicketkeeper batsman famous for his high-energy scream screams" },
  { id: "cc_58", word: "তামিম ইকবাল", englishTranslit: "Tamim Iqbal", tabooWords: ["ক্রিকেট", "চট্টগ্রাম", "পেসার", "ব্যাট"], category: "celebrities_creators", funHint: "Chittagong-born left handed explosive opening batsman of national cricket" },
  { id: "cc_59", word: "মুস্তাফিজুর রহমান", englishTranslit: "Mustafizur Rahman", tabooWords: ["কাটার", "পেসার", "ক্রিকেট", "আইপিএল"], category: "celebrities_creators", funHint: "The 'Fizz' famously known for his lethal off-cutters and IPL wickets" },
  { id: "cc_60", word: "কিলিয়ান এমবাপ্পে", englishTranslit: "Kylian Mbappe", tabooWords: ["ফুটবল", "ফ্রান্স", "গতি", "রিয়াল"], category: "celebrities_creators", funHint: "French football speed demon who recently transferred to Real Madrid" },
  { id: "cc_61", word: "এলহিং হালান্ড", englishTranslit: "Erling Haaland", tabooWords: ["সিটি", "ফুটবল", "গোল", "নরওয়ে"], category: "celebrities_creators", funHint: "Nordic machine-like giant striker scoring endless goals for Manchester City" },
  { id: "cc_62", word: "সেরেনা উইলিয়ামস", englishTranslit: "Serena Williams", tabooWords: ["টেনিস", "আমেরিকা", "মহিলা", "র‌্যাকেট"], category: "celebrities_creators", funHint: "The undisputed queen of modern female tennis champion history" },
  { id: "cc_63", word: "রজার ফেদেরার", englishTranslit: "Roger Federer", tabooWords: ["টেনিস", "কোর্ট", "সুইজারল্যান্ড", "চ্যাম্পিয়ন"], category: "celebrities_creators", funHint: "The elegant Swiss tennis icon celebrated for his precise one hand backhands" },
  { id: "cc_64", word: "ক্রিস্টোফার নোলান", englishTranslit: "Christopher Nolan", tabooWords: ["পরিচালক", "মুভি", "সময়", "ক্যামেরা"], category: "celebrities_creators", funHint: "Movie direct master who avoids computer graphics visuals and plays with time dimensions" },
  { id: "cc_65", word: "মার্গট রবি", englishTranslit: "Margot Robbie", tabooWords: ["বার্বি", "অভিনেত্রী", "হার্লি", "অস্ট্রেলিয়া"], category: "celebrities_creators", funHint: "Aesthetic Australian actress who played Harley Quinn and real life Barbie" },
  { id: "cc_66", word: "কিলিয়ান মারফি", englishTranslit: "Cillian Murphy", tabooWords: ["অভিনেতা", "পিকি", "চক্ষু", "ওপেনহাইমার"], category: "celebrities_creators", funHint: "Irish actor with striking blue eyes, famous for Peaky Blinders and Oppenheimer" },
  { id: "cc_67", word: "ডুয়া লিপা", englishTranslit: "Dua Lipa", tabooWords: ["গান", "পপ", "লন্ডন", "লেভিটেটিং"], category: "celebrities_creators", funHint: "British-Albanian pop goddess who sang Levitating and New Rules" },
  { id: "cc_68", word: "জুলকারনাইন সায়ের", englishTranslit: "Zulkarnain Saer", tabooWords: ["ফেসবুক", "খোলা", "সাংবাদিক", "লন্ডন"], category: "celebrities_creators", funHint: "UK-based investigative reporter known for dramatic live video broadcasts on Facebook" },
  { id: "cc_69", word: "মুফতি মেনক", englishTranslit: "Mufti Menk", tabooWords: ["বক্তা", "ইসলামী", "দাওয়া", "লেকচার"], category: "celebrities_creators", funHint: "Cheerful global Islamic scholar famous for his lighthearted, motivational speech style" },
  { id: "cc_70", word: "সন্দীপ মহেশ্বরী", englishTranslit: "Sandeep Maheshwari", tabooWords: ["মোটিভেশন", "ইউটিউব", "ভারত", "সেমিনার"], category: "celebrities_creators", funHint: "Indian speaker who triggers you with 'Asaan Hai!' (it is easy!) tagline" },
  { id: "cc_71", word: "টেকনিক্যাল গুরুজি", englishTranslit: "Technical Guruji", tabooWords: ["মোবাইল", "টেক", "হিন্দি", "রিভিউ"], category: "celebrities_creators", funHint: "Gaurav Chaudhary who opens tech review videos with 'Chaliye Shuru Karte Hain'" },
  { id: "cc_72", word: "জো বাইডেন", englishTranslit: "Joe Biden", tabooWords: ["আমেরিকা", "প্রেসিডেন্ট", "হোয়াইট", "বুড়ো"], category: "celebrities_creators", funHint: "The current elderly president of USA living in the White House" },
  { id: "cc_73", word: "ডোনাল্ড ট্রাম্প", englishTranslit: "Donald Trump", tabooWords: ["প্রেসিডেন্ট", "আমেরিকা", "চুল", "কোম্পানি"], category: "celebrities_creators", funHint: "Sassy Orange haired US billionaire politician who wants to make America great again" },
  { id: "cc_74", word: "ইলন মাস্ক", englishTranslit: "Elon Musk", tabooWords: ["টুইটার", "টেসলা", "রকেট", "স্পেসএক্স"], category: "celebrities_creators", funHint: "Rich eccentric billionaire who bought Twitter and renamed it simply to 'X'" },
  { id: "cc_75", word: "জেফ বেজোস", englishTranslit: "Jeff Bezos", tabooWords: ["আমাজন", "ধনী", "মহাকাশ", "টাকেন"], category: "celebrities_creators", funHint: "Bald billionaire who founded Amazon package delivery service in his garage" },
  { id: "cc_76", word: "মাশরাফি জুনিয়র", englishTranslit: "Mashrafe Junior", tabooWords: ["ছেলে", "ক্রিকেট", "নড়াইল", "অধিনায়ক"], category: "celebrities_creators", funHint: "Colloquial tribute sports fans give to young energetic fast bowlers who remind them of Mash" },
  { id: "cc_77", word: "আর. ডি. বর্মন", englishTranslit: "RD Burman", tabooWords: ["গান", "বলিউড", "সুর", "পুরানো"], category: "celebrities_creators", funHint: "Legendary retro Bollywood music director who used cold drink bottles to create sound rhythms" },
  { id: "cc_78", word: "তসলিমা নাসরিন", englishTranslit: "Taslima Nasrin", tabooWords: ["বই", "নির্বাসন", "লজ্জা", "লেখক"], category: "celebrities_creators", funHint: "Controversial Bangladeshi feminist novelist who has been living in exile for decades" },
  { id: "cc_79", word: "জাফর ইকবাল", englishTranslit: "Jafor Iqbal", tabooWords: ["বিজ্ঞান", "বই", "গল্প", "শাহজালাল"], category: "celebrities_creators", funHint: "Legendary science fiction author who wrote Dipu Number Two and taught at SUST" },
  { id: "cc_80", word: "ড. ইউনূস", englishTranslit: "Muhammad Yunus", tabooWords: ["নোবেল", "ব্যাংক", "গ্রামীণ", "দরিদ্র"], category: "celebrities_creators", funHint: "Bangladesh's microcredit pioneer who won the Nobel Peace Prize for Grameen Bank" },

  // ==================================================
  // CATEGORY 3: DHAKA_MEMES_SLANG (80 unique cards)
  // ==================================================
  { id: "dm_1", word: "খেলা হবে", englishTranslit: "Khela Hobe", tabooWords: ["রাজনীতি", "শামীম", "বক্তব্য", "উত্তেজনা"], category: "dhaka_memes_slang", funHint: "The most iconic local political slogan used right before a massive faceoff" },
  { id: "dm_2", word: "ভাবা নিছেন?", englishTranslit: "Vaiba Nisen?", tabooWords: ["বোকা", "স্মার্ট", "জিজ্ঞাসা", "বুঝেছি"], category: "dhaka_memes_slang", funHint: "When someone thinks you're clueless but you are secretly 10 steps ahead" },
  { id: "dm_3", word: "প্যারা নাই চিল", englishTranslit: "Pera Nai Chill", tabooWords: ["সমস্যা", "টেনশন", "শান্তি", "লাইফ"], category: "dhaka_memes_slang", funHint: "The ultimate survival life philosophy of every Bangladeshi student before class finals" },
  { id: "dm_4", word: "পারবে না রিকশা চালাতে", englishTranslit: "Parbe na rishka chalate", tabooWords: ["ভার্সিটি", "পড়ালেখা", "খারাপ", "চাকরি"], category: "dhaka_memes_slang", funHint: "The standard extreme doom threat Bangladeshi parents give you when your report card is bad" },
  { id: "dm_5", word: "আস্তে লেডিস", englishTranslit: "Aste Ladis", tabooWords: ["মেয়ে", "বাস", "রাস্তা", "মহিলা"], category: "dhaka_memes_slang", funHint: "Dhaka local bus helper shouting out warnings to ladies descending carefully" },
  { id: "dm_6", word: "ব্রো ভাই", englishTranslit: "Bro Bhai", tabooWords: ["বন্ধু", "দোস্ত", "ভাইয়া", "আড্ডা"], category: "dhaka_memes_slang", funHint: "Double redundancy of code brotherhood used during casual street corner tea talks" },
  { id: "dm_7", word: "কোপা শামসু", englishTranslit: "Kopa Samsu", tabooWords: ["পুরানো", "কাটা", "অস্থির", "স্টাইল"], category: "dhaka_memes_slang", funHint: "Old school 2000s meme slangs to describe ultimate violent styling action" },
  { id: "dm_8", word: "আলগা পিরিতি", englishTranslit: "Alga Piriti", tabooWords: ["প্রেম", "মিথ্যা", "নাটক", "বন্ধু"], category: "dhaka_memes_slang", funHint: "Exaggerated fake sweet words from a toxic passive-aggressive class mate" },
  { id: "dm_9", word: "ক্র্যাশ খাওয়া", englishTranslit: "Crash khawa", tabooWords: ["পছন্দ", "মেয়ে", "ছেলে", "লাজুক"], category: "dhaka_memes_slang", funHint: "Instantly falling in love with a random stranger you saw on the 13A route bus" },
  { id: "dm_10", word: "পিনিক", englishTranslit: "Pinik", tabooWords: ["নেশা", "চা", "উত্তেজনা", "জোস"], category: "dhaka_memes_slang", funHint: "The supreme energetic euphoria you feel after drinking hot pepper-ginger Tong tea" },
  { id: "dm_11", word: "লুল", englishTranslit: "Lul", tabooWords: ["হাসি", "বোকা", "পাগল", "ফেসবুক"], category: "dhaka_memes_slang", funHint: "Slang term to describe a funny, hyper-flirty, slightly creepy social comment" },
  { id: "dm_12", word: "খাইসে আমারে!", englishTranslit: "Khaise amare!", tabooWords: ["বিপদ", "খাওয়া", "অবাক", "সর্বনাশ"], category: "dhaka_memes_slang", funHint: "Standard Dhakaiya exclamation of extreme shock when plans fail miserably" },
  { id: "dm_13", word: "কেমন জানি লাগতেছে", englishTranslit: "Kemon jani lagteche", tabooWords: ["অবস্থা", "মন", "খারাপ", "অসুস্থ"], category: "dhaka_memes_slang", funHint: "Slightly uncomfortable vibe check phrase when things feel fishy or out of place" },
  { id: "dm_14", word: "মামা জোস", englishTranslit: "Mama Joss", tabooWords: ["জোরদার", "অস্থির", "দারুণ", "বন্ধু"], category: "dhaka_memes_slang", funHint: "The universal compliment for an amazing haircut, new watch, or cool jacket" },
  { id: "dm_15", word: "ফাঁকা বাঁশ", englishTranslit: "Faka bash", tabooWords: ["বিপদ", "লড়াই", "ধোঁকা", "সমস্যা"], category: "dhaka_memes_slang", funHint: "When you get severely backstabbed by someone you trusted with assignments" },
  { id: "dm_16", word: "কপালে শনি", englishTranslit: "Kopale shoni", tabooWords: ["ভাগ্য", "খারাপ", "বিপদ", "নষ্ট"], category: "dhaka_memes_slang", funHint: "When a major crisis is approaching because dad saw your search history" },
  { id: "dm_17", word: "বাঁশ খাওয়া", englishTranslit: "Bash khawa", tabooWords: ["বিপদ", "সমস্যা", "ভুক্তভোগী", "ধোঁকা"], category: "dhaka_memes_slang", funHint: "Slang to express that you have been dealt a heavy, painful blow by life" },
  { id: "dm_18", word: "কপিক্যাট", englishTranslit: "Copycat", tabooWords: ["নকল", "পরীক্ষা", "খাতা", "বিড়াল"], category: "dhaka_memes_slang", funHint: "Uncreative classmate copy pasting your whole exam script including mistakes" },
  { id: "dm_19", word: "রিকরোল", englishTranslit: "Rickroll", tabooWords: ["গান", "লিংক", "ইউটিউব", "রিক"], category: "dhaka_memes_slang", funHint: "Classic internet trick sending dummy links that boot Rick Astley's dance track" },
  { id: "dm_20", word: "ডোগ কার্টুন", englishTranslit: "Doge", tabooWords: ["কুকুর", "মিম", "টাকা", "হলুদ"], category: "dhaka_memes_slang", funHint: "The iconic sideways glancing yellow Shiba Inu dog who represents crypto money memes" },
  { id: "dm_21", word: "জাপানি ডল", englishTranslit: "Grumpy Cat", tabooWords: ["বিড়াল", "রাগ", "মিম", "খারাপ"], category: "dhaka_memes_slang", funHint: "The permanently angry white-and-gray cat with massive frown lines" },
  { id: "dm_22", word: "গিগাচ্যাড", englishTranslit: "Gigachad", tabooWords: ["পুরুষ", "সুন্দর", "বডি", "পেশী"], category: "dhaka_memes_slang", funHint: "The gray jawline model representing absolute masculine security and confidence" },
  { id: "dm_23", word: "মনোযোগ আকর্ষককারী", englishTranslit: "Distracted Boyfriend", tabooWords: ["প্রেমিক", "প্রেমিকা", "মেয়ে", "রাস্তা"], category: "dhaka_memes_slang", funHint: "Boy holds hands with his angry partner while intensely staring back at another girl" },
  { id: "dm_24", word: "সাইড আই", englishTranslit: "Side Eye", tabooWords: ["চোখ", "তাকানো", "সন্দেহ", "মেম"], category: "dhaka_memes_slang", funHint: "Visual expression of absolute judgment, suspicion, and dynamic disapproval" },
  { id: "dm_25", word: "ট্রোলফেস", englishTranslit: "Trollface", tabooWords: ["হাসি", "নকল", "পুরানো", "মিম"], category: "dhaka_memes_slang", funHint: "Early internet creepy wide-smiling face used to tease people after a prank" },
  { id: "dm_26", word: "পিপ দ্য ফ্রগ", englishTranslit: "Pepe the Frog", tabooWords: ["ব্যাঙ", "সবুজ", "কান্না", "ইন্টারনেট"], category: "dhaka_memes_slang", funHint: "The sad green internet frog showing extremely relatable depression states" },
  { id: "dm_27", word: "হাইড দ্য পেইন হ্যারল্ড", englishTranslit: "Harold", tabooWords: ["দাদু", "হাসি", "কান্না", "কষ্ট"], category: "dhaka_memes_slang", funHint: "The elderly computer stock photo dad smiling awkwardly while hiding severe depression" },
  { id: "dm_28", word: "বুমো মোমেন্ট", englishTranslit: "Bruh", tabooWords: ["শব্দ", "হতাশা", "বন্ধু", "অনুরোধ"], category: "dhaka_memes_slang", funHint: "That deep physical sound and sigh you make when things are too goofy to believe" },
  { id: "dm_29", word: "নো ক্যাপ", englishTranslit: "No Cap", tabooWords: ["মিথ্যা", "টুপি", "সত্যি", "স্ল্যাং"], category: "dhaka_memes_slang", funHint: "Gen-Z phrase meaning 'I swear I am telling 100% pure truth, no lies'" },
  { id: "dm_30", word: "রিজবান", englishTranslit: "Rizz", tabooWords: ["প্রেম", "কথা", "ক্যারিশমা", "মেয়ে"], category: "dhaka_memes_slang", funHint: "Your insane charismatic charm and verbal game to attract opposite romantic interests" },
  { id: "dm_31", word: "স্কিবিডি", englishTranslit: "Skibidi", tabooWords: ["টয়লেট", "বাচ্চা", "ইউটিউব", "মাথা"], category: "dhaka_memes_slang", funHint: "Brain rot meme of a human head singing inside a porcelain flush toilet bowl" },
  { id: "dm_32", word: "গ্যাটম্যান", englishTranslit: "Gyatt", tabooWords: ["মোটা", "মেয়ে", "পিছন", "অবাক"], category: "dhaka_memes_slang", funHint: "Internet exclamation of awe when witnessing an extremely curvy posture" },
  { id: "dm_33", word: "হক টুয়াহ", englishTranslit: "Hawk Tuah", tabooWords: ["মেয়ে", "ভিডিও", "থুতু", "ভাইরাল"], category: "dhaka_memes_slang", funHint: "The viral street interview girl describing how to spit on that thing" },
  { id: "dm_34", word: "অতিশয় ভদ্র", englishTranslit: "Very Demure", tabooWords: ["ভদ্র", "নাজুক", "মেয়ে", "টিকটক"], category: "dhaka_memes_slang", funHint: "Doing things in a very formal, modest, and highly mindful aesthetic category" },
  { id: "dm_35", word: "মারিও", englishTranslit: "Mario", tabooWords: ["নিন্টেন্ডো", "লাফ", "মাশরুম", "গেমিং"], category: "dhaka_memes_slang", funHint: "Mustache wearing Italian plumber jumping over turtles to save princess Peach" },
  { id: "dm_36", word: "সনিক", englishTranslit: "Sonic", tabooWords: ["হেজহগ", "নীল", "দ্রুত", "রিং"], category: "dhaka_memes_slang", funHint: "Lightning fast blue hedgehog collecting gold rings across green zone loops" },
  { id: "dm_37", word: "ক্রাটোস", englishTranslit: "Kratos", tabooWords: ["তলওয়ার", "প্লেস্টেশন", "দেবতা", "গ্রীক"], category: "dhaka_memes_slang", funHint: "The angry ash-colored Ghost of Sparta who slaughters Olympian gods" },
  { id: "dm_38", word: "মাস্টার চিফ", englishTranslit: "Master Chief", tabooWords: ["এক্সবক্স", "হেলমেট", "মহাকাশ", "হেলো"], category: "dhaka_memes_slang", funHint: "Helmet wearing green cyber soldier defending galaxy against covenant aliens" },
  { id: "dm_39", word: "লারা ক্রফ্‌ট", englishTranslit: "Lara Croft", tabooWords: ["কবর", "বন্দুক", "অ্যাডভেঞ্চার", "নারী"], category: "dhaka_memes_slang", funHint: "Double pistol wielding aristocrat archaeologist who loots ancient tombs" },
  { id: "dm_40", word: "জেরাল্ট", englishTranslit: "Geralt", tabooWords: ["উইচার", "চুল", "রাক্ষস", "তলোয়ার"], category: "dhaka_memes_slang", funHint: "White haired mutant monster hunter carrying two swords on his back" },
  { id: "dm_41", word: "প্যাক-ম্যান", englishTranslit: "Pac-Man", tabooWords: ["হলুদ", "ভুত", "খাওয়া", "আর্কেড"], category: "dhaka_memes_slang", funHint: "Yellow circular mouth eating dots inside a dark arcade maze chased by ghosts" },
  { id: "dm_42", word: "মাইনক্রাফট স্টিভ", englishTranslit: "Minecraft Steve", tabooWords: ["ব্লক", "আঁকা", "খনি", "ক্রিপার"], category: "dhaka_memes_slang", funHint: "The default blue shirt bloke in a blocky cubical world digging pixel gems" },
  { id: "dm_43", word: "এজেন্ট ৪৭", englishTranslit: "Agent 47", tabooWords: ["টাক", "হিটম্যান", "পিস্তল", "বারকোড"], category: "dhaka_memes_slang", funHint: "Bald suit assassin with a barcodes tattoo stamped on his neck back" },
  { id: "dm_44", word: "সিজে জিটিএ", englishTranslit: "CJ GTA", tabooWords: ["কার্ল", " লস", "সাইকেল", "গেম"], category: "dhaka_memes_slang", funHint: "Carl Johnson who complains 'Ah, here we go again' in Grove Street" },
  { id: "dm_45", word: "আর্থার মরগান", englishTranslit: "Arthur Morgan", tabooWords: ["ঘোড়া", "কাউবয়", "ডাচ", "ডাকাতি"], category: "dhaka_memes_slang", funHint: "Tragic outlaw cowboy riding horses across wild west America in Red Dead" },
  { id: "dm_46", word: "পিকাচু কার্টুন", englishTranslit: "Pikachu", tabooWords: ["হলুদ", "ইঁদুর", "কার্টুন", "কারেন্ট"], category: "dhaka_memes_slang", funHint: "The spiky red-cheeked electric mouse who yells pika-pika!" },
  { id: "dm_47", word: "ব্যাটম্যান", englishTranslit: "Batman", tabooWords: ["বাদুড়", "ধনী", "কালো", "ব্রুস"], category: "dhaka_memes_slang", funHint: "Millionaire orphan wears a black bat suit to punch street criminals at night" },
  { id: "dm_48", word: "জোকার কার্টুন", englishTranslit: "Joker", tabooWords: ["হাসি", "ক্লৌন", "পাগল", "সবুজ"], category: "dhaka_memes_slang", funHint: "The green haired psycho villain who asks 'Why so serious?'" },
  { id: "dm_49", word: "কপ আলে শনি", englishTranslit: "Kopale Shoni Alternative", tabooWords: ["হতাশা", "মন্দ", "বিপদ", "নস্ট"], category: "dhaka_memes_slang", funHint: "Classic retro horror reference indicating high misfortune" },
  { id: "dm_50", word: "চাদের দেশে", englishTranslit: "Chader Deshe", tabooWords: ["চাঁদ", "মারা", "লাশ", "খুন"], category: "dhaka_memes_slang", funHint: "Euphemistic local slang indicating sending someone completely out of existence" },
  { id: "dm_51", word: "কপাই কাইটা", englishTranslit: "Kopai Kaita", tabooWords: ["কাটা", "অস্থির", "স্টাইল", "মারামারি"], category: "dhaka_memes_slang", funHint: "Old Dhaka threat showing ultimate dynamic chopping motions" },
  { id: "dm_52", word: "আব্বা রে আব্বা", englishTranslit: "Abba Re Abba", tabooWords: ["পিতা", "আহ্বান", "ক্লান্ত", "বিপদ"], category: "dhaka_memes_slang", funHint: "Dhakaiya exclamation of extreme physical exhaustion or heavy heat waves" },
  { id: "dm_53", word: "পোলাপাইন", englishTranslit: "Polapain", tabooWords: ["বাচ্চা", "ছেলে", "তরুণ", "বদমাইশ"], category: "dhaka_memes_slang", funHint: "Plural colloquial word for hyperactive kids doing weird parkour on Dhaka roofs" },
  { id: "dm_54", word: "মায়া লাগাইছে", englishTranslit: "Maya Lagaise", tabooWords: ["ভালোবাসা", "প্রেম", "আকাঙ্ক্ষা", "মেয়ে"], category: "dhaka_memes_slang", funHint: "Bengali song line describing how someone cast a beautiful aesthetic emotional spell" },
  { id: "dm_55", word: "মায়া বেশি", englishTranslit: "Maya Beshi", tabooWords: ["ভিতর", "কষ্ট", "দুর্বল", "প্রেমী"], category: "dhaka_memes_slang", funHint: "When you have too much soft emotional bonding with street cats or toxic exes" },
  { id: "dm_56", word: "রিকি কার্টুন", englishTranslit: "Rick and Morty", tabooWords: ["দাদু", "পাগল", "মহাকাশ", "রসায়ন"], category: "dhaka_memes_slang", funHint: "Burping alcohol grandfather drags his nervous grandson through galaxy portals" },
  { id: "dm_57", word: "চুম্বক চালক", englishTranslit: "Magneto", tabooWords: ["মার্ভেল", "লোহা", "এক্সম্যান", "আকর্ষণ"], category: "dhaka_memes_slang", funHint: "X-Men supervillain who can slide massive iron bridge spans using brain waves" },
  { id: "dm_58", word: "ডিটেকটিভ কনান", englishTranslit: "Detective Conan", tabooWords: ["বাচ্চা", "চশমা", "ওষুধ", "কেস"], category: "dhaka_memes_slang", funHint: "Japanese high school genius shrunk into a child body who solves crimes with watch darts" },
  { id: "dm_59", word: "পোপি দ্য সেলর", englishTranslit: "Popeye", tabooWords: ["পালং", "শাক", "শক্তি", "জাহাজ"], category: "dhaka_memes_slang", funHint: "Sailor cartoon who eats canned spinach to gain massive super strength instantly" },
  { id: "dm_60", word: "চাচা চৌধুরী", englishTranslit: "Chacha Chaudhary", tabooWords: ["মগজ", "সাবু", "ভারত", "কম্পিউটার"], category: "dhaka_memes_slang", funHint: "Classic comic book uncle whose brain works faster than an actual computer" },
  { id: "dm_61", word: "সুপারম্যান", englishTranslit: "Superman", tabooWords: ["লাল", "নীল", "পাথর", "ফ্লাই"], category: "dhaka_memes_slang", funHint: "Alien hero in blue suit wearing underpants outside, weak to green kryptonite stones" },
  { id: "dm_62", word: "গোকু কার্টুন", englishTranslit: "Goku", tabooWords: ["চুল", "শহীদ", "বল", "উড়া"], category: "dhaka_memes_slang", funHint: "Saiyan hero of Dragon Ball who does the blue energy wave Kamehameha" },
  { id: "dm_63", word: "কঙ্কাল ভুত", englishTranslit: "Skeleton meme", tabooWords: ["মৃত", "হাড়", "হাসি", "ভয়"], category: "dhaka_memes_slang", funHint: "Spooky dance bones representing waiting decades for a crash reply" },
  { id: "dm_64", word: "শেক্সপিয়ার", englishTranslit: "Shakespeare", tabooWords: ["কবি", "নাটক", "রোমিও", "লেখক"], category: "dhaka_memes_slang", funHint: "English classic playwright who asked 'To be or not to be'" },
  { id: "dm_65", word: "ডার্থ ভেডার", englishTranslit: "Darth Vader", tabooWords: ["কালো", "হেলমেট", "লুক", "পিতা"], category: "dhaka_memes_slang", funHint: "Sci-fi black helmet villain who breathes heavily and reveals 'I am your father'" },
  { id: "dm_66", word: "ইভান কার্টুন", englishTranslit: "Evangelion", tabooWords: ["রোবট", "এঞ্জেল", "শিনজি", "জাপানি"], category: "dhaka_memes_slang", funHint: "Depressed mech teenage pilot Shinji fights giant biological angels coming from ocean" },
  { id: "dm_67", word: "শামসু ভাই", englishTranslit: "Shamsu Bhai", tabooWords: ["মিম", "পুরানো", "বন্ধু", "দাদু"], category: "dhaka_memes_slang", funHint: "Generic local neighborhood gaming companion often blamed for poor tactical plays" },
  { id: "dm_68", word: "পাবজি নোব", englishTranslit: "PUBG Noob", tabooWords: ["গেম", "গুলি", "নষ্ট", "মোবাইল"], category: "dhaka_memes_slang", funHint: "Terrible squad mate who dies in 10 seconds and demands revive repeatedly" },
  { id: "dm_69", word: "ক্লাশ অফ ক্ল্যান্স", englishTranslit: "Clash of Clans", tabooWords: ["সেনা", "গোত্র", "রানী", "খেলা"], category: "dhaka_memes_slang", funHint: "Pioneering layout strategy mobile game where you build village defense cannons" },
  { id: "dm_70", word: "ফ্রি ফায়ার", englishTranslit: "Free Fire", tabooWords: ["মোবাইল", "গুলি", "অস্থির", "খেলা"], category: "dhaka_memes_slang", funHint: "Extremely popular battle royale game kids play outdoors in squads" },
  { id: "dm_71", word: "ফাকা আওয়াজ", englishTranslit: "Faka Awaj", tabooWords: ["চুরি", "ঝগড়া", "ভয়", "মিথ্যা"], category: "dhaka_memes_slang", funHint: "Empty loud threats without actual execution power or backup" },
  { id: "dm_72", word: "ওঠা বসা", englishTranslit: "Otha Bosa", tabooWords: ["ব্যায়াম", " শাস্তি", "কান", "ইশকুল"], category: "dhaka_memes_slang", funHint: "Holding your ears while squatting down as punishment in local government schools" },
  { id: "dm_73", word: "ছবি উঠাই", englishTranslit: "Chobi Uthai", tabooWords: ["ক্যামেরা", "ফেসবুক", "মোবাইল", "চেহারা"], category: "dhaka_memes_slang", funHint: "Urgent request to snap high angle smartphone photos for social feed flexing" },
  { id: "dm_74", word: "ব্যাগ কাধ", englishTranslit: "Bag Kadh", tabooWords: ["ব্যাগ", "ভার্সিটি", "পড়ালেখা", "রাস্তা"], category: "dhaka_memes_slang", funHint: "Slang for university freshmen roaming the campus looking utterly lost" },
  { id: "dm_75", word: "বড় লোক", englishTranslit: "Borolok", tabooWords: ["টাকা", "গাড়ি", "ধনী", "গুলশান"], category: "dhaka_memes_slang", funHint: "Dhanmondi or Gulshan rich folks who speak English accents at premium coffee shops" },
  { id: "dm_76", word: "মাঝারি ফন্ট", englishTranslit: "Medium Font", tabooWords: ["লেখা", " ফন্ট", "আকার", "বড়"], category: "dhaka_memes_slang", funHint: "Typographical term transformed into jokes about intermediate class performers" },
  { id: "dm_77", word: "খালি কলসি", englishTranslit: "Khali Kolsi", tabooWords: ["পানি", "আওয়াজ", "শব্দ", " ফাকা"], category: "dhaka_memes_slang", funHint: "Proverial phrase explaining empty vessels sound much louder" },
  { id: "dm_78", word: "তেল মারা", englishTranslit: "Tel Mara", tabooWords: ["প্রশংসা", " চাটুকার", "মিথ্যা", "অফিস"], category: "dhaka_memes_slang", funHint: "Buttering up senior bosses inside offices to gain positive appraisal reviews" },
  { id: "dm_79", word: "আকাশে মেঘ", englishTranslit: "Akashe Megh", tabooWords: ["বৃষ্টি", "কালো", "ছাতা", "পানি"], category: "dhaka_memes_slang", funHint: "Romantic excuse to play emotional lofi tracks on late rainy night drives" },
  { id: "dm_80", word: "জিপিএ ফাইভ", englishTranslit: "GPA 5", tabooWords: ["মিষ্টি", "পরীক্ষা", "গোল্ডেন", "ভাল"], category: "dhaka_memes_slang", funHint: "The supreme metric of family validation, golden grade aunts brag about continuously" },

  // ===============================================
  // CATEGORY 4: FOOD_CULTURE (80 unique cards)
  // ===============================================
  { id: "fc_1", word: "কাচ্চি বিরিয়ানি", englishTranslit: "Kachchi Biryani", tabooWords: ["খাসি", "বাসমতি", "আলু", "বিয়ে"], category: "food_culture", funHint: "The undisputed Emperor of Dhaka feast, layered with ghee-bathed mutton and a massive potato" },
  { id: "fc_2", word: "ফুচকা", englishTranslit: "Fuchka", tabooWords: ["টক", "ঝাল", "আলু", "তেঁতুল"], category: "food_culture", funHint: "Crispy hollow spheres stuffed with spiced chickpea mash and filled with cold sour tamarind water" },
  { id: "fc_3", word: "চটপটি", englishTranslit: "Chotpoti", tabooWords: ["ডাল", "ডিম", "মশলা", "তেঁতুল"], category: "food_culture", funHint: "Tangy chickpea bowl sprinkled with grated hardboiled egg and crushed crispy shell crumbs" },
  { id: "fc_4", word: "মোরগ পোলাও", englishTranslit: "Morog Polao", tabooWords: ["মুরগি", "ডিম", "বিয়ে", "পোলাও"], category: "food_culture", funHint: "Traditional wedding feast plate features delicious ghee rice and a massive spiced chicken leg" },
  { id: "fc_5", word: "বাকরখানি", englishTranslit: "Bakarkhani", tabooWords: ["চা", "মিষ্টি", "পুরান", "বিস্কুট"], category: "food_culture", funHint: "Unique crunchy layered flour biscuit bread, the deep pride of Old Dhaka tea subcultures" },
  { id: "fc_6", word: "গরু তেহারি", englishTranslit: "Beef Tehari", tabooWords: ["সরিষা", "তেল", "গরু", "ছোট"], category: "food_culture", funHint: "Spiced aromatic short米 rice cooked with small beef chunks bathed in pure mustard oil" },
  { id: "fc_7", word: "চা-সিঙারা", englishTranslit: "Cha-Shingara", tabooWords: ["টং", "আড্ডা", "গরম", "আলু"], category: "food_culture", funHint: "The absolute gold standard afternoon snack combination pairing in street tea corners" },
  { id: "fc_8", word: "পান্তা ইলিশ", englishTranslit: "Panta Ilish", tabooWords: ["বৈশাখ", "পহেলা", "ইলিশ", "পানি"], category: "food_culture", funHint: "Day-old fermented water rice paired with fried Hilsa fish, consumed on Pohela Boishakh" },
  { id: "fc_9", word: "কালা ভুনা", englishTranslit: "Kala Bhuna", tabooWords: ["মেজবান", "কালো", "গরু", "পেঁয়াজ"], category: "food_culture", funHint: "Chittagong's legendary block-dark slow oil roasted beef packed with secret spices" },
  { id: "fc_10", word: "ভাপা পিঠা", englishTranslit: "Vapa Pitha", tabooWords: ["শীত", "খেঁজুর", "গুড়", "ভাপ"], category: "food_culture", funHint: "A winter special steamed rice flour cake stuffed with molten date molasses and coconut shreds" },
  { id: "fc_11", word: "রসগোলা", englishTranslit: "Rasgulla", tabooWords: ["মিষ্টি", "সাদা", "রস", "ছাতি"], category: "food_culture", funHint: "Super soft spongy circular white cottage cheese balls soaked in boiling sweet syrup" },
  { id: "fc_12", word: "চটপটি ফুচকা", englishTranslit: "Doi Fuchka", tabooWords: ["দই", "মিষ্টি", "টক", "ফুচকা"], category: "food_culture", funHint: "Fuchka shell filled with chickpea and sweet chilled whipped yogurt with sweet sauces" },
  { id: "fc_13", word: "জিলাপি", englishTranslit: "Jilapi", tabooWords: ["মিষ্টি", "প্যাঁচ", "মচমচে", "গরম"], category: "food_culture", funHint: "Sinuous twisted spiral crispy orange tubes leaking hot sugar juice when bitten" },
  { id: "fc_14", word: "হালিম", englishTranslit: "Halim", tabooWords: ["ডাল", "মাংস", "লেবু", "বাটি"], category: "food_culture", funHint: "Slow cooked thick broth of mixed beans and beef topped with fresh ginger strips and lemon juice" },
  { id: "fc_15", word: "ঝালমুড়ি", englishTranslit: "Jhalmuri", tabooWords: ["মুড়ি", "তেল", "চানাচুর", "কাগজ"], category: "food_culture", funHint: "Spiced puffed rice tossed inside a tin container paired with mustard oil and served in paper cones" },
  { id: "fc_16", word: "সেমাই", englishTranslit: "Shemai", tabooWords: ["ঈদ", "দুধ", "লাচ্ছা", "মিষ্টি"], category: "food_culture", funHint: "Thin sweet vermicelli cooked in sweetened milk and garnished with cashews on Eid morning" },
  { id: "fc_17", word: "বোরহানি", englishTranslit: "Borhani", tabooWords: ["দই", "বিয়ে", "মসলা", "ড্রিংক"], category: "food_culture", funHint: "Spicy sour green yogurt drink seasoned with mint leaves, mustard, and black salt" },
  { id: "fc_18", word: "কুকিজ পিজ্জা", englishTranslit: "Pizza", tabooWords: ["পনির", "ইতালি", "রুটি", "সস"], category: "food_culture", funHint: "Flat circular baked Italian bread loaded with stretching cheese and pepperoni" },
  { id: "fc_19", word: "ডাবল বার্গার", englishTranslit: "Burger", tabooWords: ["মাংস", "পাউরুটি", "পনির", "ম্যাক"], category: "food_culture", funHint: "Soft circular buns sandwiching a grilled meat patty, melting cheese, and cold lettuce" },
  { id: "fc_20", word: "সুশি রোটি", englishTranslit: "Sushi", tabooWords: ["মাছ", "জাপান", "ভাত", "কাঁচা"], category: "food_culture", funHint: "Japanese signature cold rice rolls topped with raw salmon fish wrapping inside seaweeds" },
  { id: "fc_21", word: "টাকো রুটি", englishTranslit: "Taco", tabooWords: ["মেক্সিকো", "পনির", "ক্রাঞ্চি", "ক্রিস্পি"], category: "food_culture", funHint: "U-shaped crispy corn shell stuffed with ground beef, cheese sauce, and salsa salsa" },
  { id: "fc_22", word: "পাস্তা বাটি", englishTranslit: "Pasta", tabooWords: ["সাদা", "চিজ", "নুডলস", "সস"], category: "food_culture", funHint: "Italian baked penne noodles swimming inside a super creamy white white sauce" },
  { id: "fc_23", word: "জাপানি রামেন", englishTranslit: "Ramen", tabooWords: ["নুডলস", "ডিম", "স্যুপ", "জাপান"], category: "food_culture", funHint: "Deep savory broth noodle soup topped with soft boiled egg and seaweed sheets" },
  { id: "fc_24", word: "শোয়ারমা রুটি", englishTranslit: "Shawarma", tabooWords: ["চিকেন", "রুটি", "রোস্ট", " রোল"], category: "food_culture", funHint: "Shaved grilled chicken wrapped in soft pita bread with loads of garlic mayonnaise" },
  { id: "fc_25", word: "ডিম সাম", englishTranslit: "Dim Sum", tabooWords: ["মমো", "ভাপ", "চীন", "সস"], category: "food_culture", funHint: "Steamed Chinese pocket pouch dumplings filled with seasoned chicken served in bamboo baskets" },
  { id: "fc_26", word: "হট ডগ", englishTranslit: "Hot Dog", tabooWords: ["সসেজ", "রুটি", "সরিষা", "সস"], category: "food_culture", funHint: "Long cylinder grilled sausage fitted inside a sliced vertical bun with yellow mustard" },
  { id: "fc_27", word: "আলু ভাজা", englishTranslit: "French Fries", tabooWords: ["আলু", "ক্রিস্পি", "লবণ", "ভাজা"], category: "food_culture", funHint: "Crispy golden fried potato sticks sprinkled with high salt and dipped in ketchup" },
  { id: "fc_28", word: "ক্রোয়েস্যান্ট", englishTranslit: "Croissant", tabooWords: ["ফ্রান্স", "মাখন", "রুটি", "ফরাসি"], category: "food_culture", funHint: "Flaky crescent moon-shaped buttery pastry from Paris bakery shops" },
  { id: "fc_29", word: "রসমালাই", englishTranslit: "Roshomalai", tabooWords: ["কুমিল্লা", "মিষ্টি", "দুধ", "ছোট"], category: "food_culture", funHint: "Tiny sweet cottage cheese balls floating inside thick condensed clotted milk" },
  { id: "fc_30", word: "মিষ্টি দই", englishTranslit: "Sweet Yogurt", tabooWords: ["বগুড়া", "দই", "মাটি", "মিষ্টি"], category: "food_culture", funHint: "Thick caramelized brown sweet fermented milk set inside a classic clay pot" },
  { id: "fc_31", word: "ঢাকা টিএসসি", englishTranslit: "Dhaka TSC", tabooWords: ["ভার্সিটি", "চা", "আড্ডা", "টিএসসি"], category: "food_culture", funHint: "The ultimate cultural hub of Dhaka University, famous for student debates and tea" },
  { id: "fc_32", word: "কক্সবাজার", englishTranslit: "Cox's Bazar", tabooWords: ["সমুদ্র", "বালু", "পাহাড়", "হোটেল"], category: "food_culture", funHint: "The world's longest unbroken natural sandy sea beach located in Bangladesh" },
  { id: "fc_33", word: "লালবাগ কেল্লা", englishTranslit: "Lalbagh Fort", tabooWords: ["পরী", "মোঘল", "কেল্লা", "পুরান"], category: "food_culture", funHint: "Unfinished 17th-century Mughal fort structure housing daughter Pari Bibi tomb" },
  { id: "fc_34", word: "আইফেল টাওয়ার", englishTranslit: "Eiffel Tower", tabooWords: ["প্যারিস", "লোহা", "ফ্রান্স", "উচ্চ"], category: "food_culture", funHint: "The massive grid iron tower standing tall near Seine River in romantic Paris" },
  { id: "fc_35", word: "তাজমহল", englishTranslit: "Taj Mahal", tabooWords: ["আগ্রা", "শাহজাহান", "সাদা", "পাথর"], category: "food_culture", funHint: "The white marble Mughal love mausoleum Shah Jahan built for wife Mumtaz" },
  { id: "fc_36", word: "নিউইয়র্ক টাইমস স্কয়ার", englishTranslit: "Times Square", tabooWords: ["আলোক", "বিলবোর্ড", "যুক্তরাষ্ট্র", "রাস্তা"], category: "food_culture", funHint: "Hyperactive neon lit intersection of Manhattan flashing massive commercial ads" },
  { id: "fc_37", word: "লন্ডন আই", englishTranslit: "London Eye", tabooWords: ["চাকা", "লন্ডন", "নদী", " পর্যটক"], category: "food_culture", funHint: "The massive slow revolving giant observation wheel standing over River Thames" },
  { id: "fc_38", word: "চীনের প্রাচীর", englishTranslit: "Great Wall of China", tabooWords: ["পাথর", "চীন", "দেয়াল", "ম্যাপ"], category: "food_culture", funHint: "Ancient defensive stone wall stretching thousands of miles across mountain borders" },
  { id: "fc_39", word: "মিশরের পিরামিড", englishTranslit: "Pyramids of Giza", tabooWords: ["ধূলি", "মমি", "ফারাও", "পাথর"], category: "food_culture", funHint: "Colossal triangular stone structures housing the mummified bodies of ancient pharaohs" },
  { id: "fc_40", word: "বুর্জ খলিফা", englishTranslit: "Burj Khalifa", tabooWords: ["দুবাই", "উচ্চ", "টাওয়ার", "ধনী"], category: "food_culture", funHint: "The absolute tallest metal-and-glass skyscrapers needle structure in Dubai" },
  { id: "fc_41", word: "ইউটিউব", englishTranslit: "YouTube", tabooWords: ["ভিডিও", "সাবস্ক্রাইব", "চ্যানেল", "লাল"], category: "food_culture", funHint: "The red-button logo video platform where you watch endless tutorials and tutorials" },
  { id: "fc_42", word: "ফেসবুক", englishTranslit: "Facebook", tabooWords: ["লাইক", "পোস্ট", "নীল", "সোশ্যাল"], category: "food_culture", funHint: "The master blue social platform aunts use to share good morning floral pictures" },
  { id: "fc_43", word: "ইনস্টাগ্রাম", englishTranslit: "Instagram", tabooWords: ["ফেড", "ফিল্টার", "ছবি", "রিলস"], category: "food_culture", funHint: "The aesthetic photo grid app where everyone pretends to live their best luxury life" },
  { id: "fc_44", word: "টিকটক", englishTranslit: "TikTok", tabooWords: ["ভিডিও", "নাচ", "ভাইরাল", "চীন"], category: "food_culture", funHint: "Short video music app where people dance to viral fast sped-up tracks" },
  { id: "fc_45", word: "হোয়াটসঅ্যাপ", englishTranslit: "WhatsApp", tabooWords: ["মেসেজ", "চ্যাট", "সবুজ", "নাম্বার"], category: "food_culture", funHint: "Green circular icon chat application that replaced traditional standard cellular texting" },
  { id: "fc_46", word: "নেটফ্লিক্স", englishTranslit: "Netflix", tabooWords: ["মুভি", "সাবস্ক্রিপশন", "লাল", "পাসওয়ার্ড"], category: "food_culture", funHint: "Streaming giant whose iconic 'Ta-Dum' sound opens movie nights" },
  { id: "fc_47", word: "স্পটিফাই", englishTranslit: "Spotify", tabooWords: ["গান", "প্লেলিস্ট", "সবুজ", "পডকাস্ট"], category: "food_culture", funHint: "Green circle wave logo music player that curates your yearly Wrapped report" },
  { id: "fc_48", word: "চ্যাটজিপিটি", englishTranslit: "ChatGPT", tabooWords: ["এআই", "উত্তর", "লেখ", "ওপেনাই"], category: "food_culture", funHint: "Generative artificial bot that writes your assignments and resumes instantly" },
  { id: "fc_49", word: "অ্যাপল আইফোন", englishTranslit: "Apple iPhone", tabooWords: ["আপেল", "ক্যামেরা", "টাকা", "দামী"], category: "food_culture", funHint: "Three-eyed camera telephone that drains your bank balance but gets mirror selfies" },
  { id: "fc_50", word: "গুগল", englishTranslit: "Google", tabooWords: ["সার্চ", "ইন্টারনেট", "খুঁজ", "ম্যাপ"], category: "food_culture", funHint: "Multi-colored search engine bar that holds answers to every dumb query" },
  { id: "fc_51", word: "ম্যাকডোনাল্ডস", englishTranslit: "McDonald's", tabooWords: ["বার্গার", "হলুদ", "আলু", "আমেদের"], category: "food_culture", funHint: "Fast food chain trademarked by massive yellow golden double arches" },
  { id: "fc_52", word: "স্টারবাকস", englishTranslit: "Starbucks", tabooWords: ["কফি", "মহিলা", "কাপ", "সবুজ"], category: "food_culture", funHint: "Premium coffee brand where they write your name incorrectly on plastic cups" },
  { id: "fc_53", word: "উবার গাড়ি", englishTranslit: "Uber", tabooWords: ["গাড়ি", "রাইড", "ম্যাপ", "চালকের"], category: "food_culture", funHint: "App-triggered rental cars indicating how drivers cancel your trip repeatedly" },
  { id: "fc_54", word: "আডিডাস জুতা", englishTranslit: "Adidas", tabooWords: ["জুতা", "তিন", "লাইন", "জার্মানি"], category: "food_culture", funHint: "Sportswear brand recognized worldwide by its simple three diagonal stripes" },
  { id: "fc_55", word: "নাইকি জুতা", englishTranslit: "Nike", tabooWords: ["টিক", "জুতা", "খেলা", "স্যুইশ"], category: "food_culture", funHint: "Athletic brand with the famous checkmark swoosh logo saying Just Do It" },
  { id: "fc_56", word: "টেসলা গাড়ি", englishTranslit: "Tesla", tabooWords: ["বৈদ্যুতিক", "গাড়ি", "ইলন", "ব্যাটারি"], category: "food_culture", funHint: "Futuristic silent electric cars equipped with mammoth dashboard touch panels" },
  { id: "fc_57", word: "অ্যান্ড্রয়েড", englishTranslit: "Android", tabooWords: ["গুগল", "সবুজ", "মোবাইল", "রোবট"], category: "food_culture", funHint: "Google's open-source mobile phone software depicted by a green little robot" },
  { id: "fc_58", word: "প্লেস্টেশন", englishTranslit: "PlayStation", tabooWords: ["সনি", "গেম", "কন্ট্রোলার", "কনসোল"], category: "food_culture", funHint: "Sony's video gaming box whose hand controller features triangle and circle buttons" },
  { id: "fc_59", word: "মাইক্রোসফট", englishTranslit: "Microsoft", tabooWords: ["উইন্ডোজ", "বিল", " অফিস", "কম্পিউটার"], category: "food_culture", funHint: "Tech empire founded by Bill Gates that runs standard office excel sheets" },
  { id: "fc_60", word: "কুকিজ ওয়াফেল", englishTranslit: "Waffle", tabooWords: ["মিষ্টি", " গ্রিড", "মধু", "বেকড"], category: "food_culture", funHint: "Grid textured crispy sweet waffle bread topped with maple syrup and fruit slices" },
  { id: "fc_61", word: "মাছের কারি", englishTranslit: "Fish Curry", tabooWords: ["ইলিশ", "ঝোল", "ভাত", "মসলা"], category: "food_culture", funHint: "Traditional everyday standard lunch dish for deep native Bangladeshi families" },
  { id: "fc_62", word: "আলু ভর্তা", englishTranslit: "Alu Bhorta", tabooWords: ["গোল", "পেঁয়াজ", "সরিষা", "ডাল"], category: "food_culture", funHint: "Mashed boiled potatoes paired with pure raw mustard oil, dried red chilis, and onions" },
  { id: "fc_63", word: "শুটকি ভর্তা", englishTranslit: "Shutki Bhorta", tabooWords: ["গন্ধ", "শুকনো", "মাছ", "ঝাল"], category: "food_culture", funHint: "Extremely spicy chili mashed dried fish paste triggering strong coastal scent" },
  { id: "fc_64", word: "খাসি রেজালা", englishTranslit: "Mutton Rezala", tabooWords: ["মাংস", "বিয়ে", "ঝোল", "ঘি"], category: "food_culture", funHint: "Wedding special slow stewed mutton curry loaded with sweet yogurt gravy base" },
  { id: "fc_65", word: "লাড্ডু মিষ্টি", englishTranslit: "Laddu", tabooWords: ["গোলাকার", "হলুদ", "মিষ্টি", "বেসন"], category: "food_culture", funHint: "Gram flour round sweet balls served during traditional South Asian weddings" },
  { id: "fc_66", word: "পিৎজা হাট", englishTranslit: "Pizza Hut", tabooWords: ["রেস্টুরেন্ট", "পিজ্জা", "চিজ", " লাল"], category: "food_culture", funHint: "Red hat icon pizza dine-in joint families flocked to in early 2010s" },
  { id: "fc_67", word: "মাউন্টেড মাউন্ট এভারেস্ট", englishTranslit: "Mount Everest", tabooWords: ["হিমালয়", "নেপাল", "পাহাড়", "উচ্চ"], category: "food_culture", funHint: "The highest mountain peak above sea level, sitting on Nepal's border" },
  { id: "fc_68", word: "রোমের কলোসিয়াম", englishTranslit: "Colosseum", tabooWords: ["রোম", "লড়াই", "ইতালি", "পুরাতন"], category: "food_culture", funHint: "The giant ruined stone amphitheater where ancient gladiators fought to the death" },
  { id: "fc_69", word: "গ্র্যান্ড ক্যানিয়ন", englishTranslit: "Grand Canyon", tabooWords: ["ইউএসএ", "লাল", " নদী", "ঘাটি"], category: "food_culture", funHint: "Massive steep-sided red rock canyon carved out by Colorado River in US" },
  { id: "fc_70", word: "সিডনি অপেরা হাউস", englishTranslit: "Sydney Opera", tabooWords: ["অস্ট্রেলিয়া", "নৌকা", "সাদা", "সাংস্কৃতিক"], category: "food_culture", funHint: "Aesthetic white shell-shaped performance arts center sitting over Sydney harbor" },
  { id: "fc_71", word: "টোকিও শিবুয়া ক্রসিং", englishTranslit: "Shibuya Crossing", tabooWords: ["টোকিও", "জাপান", "রাস্তা", "পথচারী"], category: "food_culture", funHint: "The world's heaviest multi-directional pedestrian crosswalk intersections" },
  { id: "fc_72", word: "চিজকেক মিষ্টি", englishTranslit: "Cheesecake", tabooWords: ["মিষ্টি", "পনির", "বেকড", "ক্রিম"], category: "food_culture", funHint: "Decadent cream cheese baked dessert layered over a graham cracker cookie crust" },
  { id: "fc_73", word: "রসুন ব্রেড", englishTranslit: "Garlic Bread", tabooWords: ["রুটি", "রসুন", "মাখন", "পিজ্জা"], category: "food_culture", funHint: "Buttery sliced baguette spread with chopped garlic cloves and fresh herbs" },
  { id: "fc_74", word: "ম্যাকারন কুকিস", englishTranslit: "Macaron", tabooWords: ["মিষ্টি", "ফ্রান্স", "রঙিন", "বাদাম"], category: "food_culture", funHint: "Teeny elegant cream-filled almond meringue sandwich cookies from Paris" },
  { id: "fc_75", word: "বানি চৌতি", englishTranslit: "Chanachur", tabooWords: ["ঝাল", "মুড়ি", "প্যাকেট", "বিকাশ"], category: "food_culture", funHint: "Crispy fried noodle-like spicy chickpea flour mixture paired with roasted nuts" },
  { id: "fc_76", word: "চমচম মিষ্টি", englishTranslit: "Chomchom", tabooWords: ["টাঙ্গাইল", "মিষ্টি", "লাল", "মাওয়া"], category: "food_culture", funHint: "Tangail-famous oblong sweet covered in grated solid milk crumbles" },
  { id: "fc_77", word: "রাতের টং", englishTranslit: "Night Tong", tabooWords: ["চা", "আড্ডা", "রাত", "দোকান"], category: "food_culture", funHint: "Late night road-side tea talks with childhood friends under street lamps" },
  { id: "fc_78", word: "আলুর চপ", englishTranslit: "Alur Chop", tabooWords: ["আলু", "ভাজা", "ইফতার", "বেসন"], category: "food_culture", funHint: "Mashed spiced potato spheres dipped in chickpea batter and deep-fried for Iftar" },
  { id: "fc_79", word: "লাচ্ছা সেমাই", englishTranslit: "Laccha Shemai", tabooWords: ["ঈদ", "মিষ্টি", "দুধ", "ভাজা"], category: "food_culture", funHint: "Crispy thread vermicelli fried in pure ghee, served dry or with sweet milk" },
  { id: "fc_80", word: "বিয়েবাড়ির রিচ ফুড", englishTranslit: "Wedding Feast", tabooWords: ["বিয়ে", "কাচ্চি", "পোলাও", "খাবার"], category: "food_culture", funHint: "Over-the-top caloric rich dinner we stuff ourselves with at community convention centers" }
];
